import os
import subprocess
import uuid
import re
from pathlib import Path
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.enums import TA_LEFT, TA_CENTER

TEMP_DIR = Path("temp_latex")
TEMP_DIR.mkdir(exist_ok=True)

def extract_text_from_latex(latex_content: str) -> dict:
    """Extract text content from LaTeX for simple PDF rendering"""
    # Remove LaTeX commands and extract content
    text = latex_content
    
    # Extract name (usually after \name or in first section)
    name_match = re.search(r'\\name\{([^}]+)\}', text)
    name = name_match.group(1) if name_match else "Resume"
    
    # Extract sections
    sections = []
    
    # Find section headers and content
    section_pattern = r'\\section\{([^}]+)\}(.*?)(?=\\section|\\end\{document\}|$)'
    for match in re.finditer(section_pattern, text, re.DOTALL):
        section_title = match.group(1)
        section_content = match.group(2)
        
        # Clean up LaTeX commands
        content_clean = re.sub(r'\\[a-zA-Z]+(\[[^\]]*\])?(\{[^}]*\})?', '', section_content)
        content_clean = content_clean.replace('\\\\', '\n').replace('&', ' ')
        content_clean = ' '.join(content_clean.split())  # Clean whitespace
        
        if content_clean.strip():
            sections.append({'title': section_title, 'content': content_clean})
    
    return {'name': name, 'sections': sections}

def create_simple_pdf(latex_content: str) -> str:
    """Create a simple PDF from LaTeX content using reportlab"""
    session_id = str(uuid.uuid4())
    pdf_file = TEMP_DIR / f"{session_id}.pdf"
    
    # Extract content
    parsed = extract_text_from_latex(latex_content)
    
    # Create PDF
    doc = SimpleDocTemplate(str(pdf_file), pagesize=letter,
                           topMargin=0.75*inch, bottomMargin=0.75*inch,
                           leftMargin=0.75*inch, rightMargin=0.75*inch)
    
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor='black',
        spaceAfter=12,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    )
    
    section_style = ParagraphStyle(
        'SectionHeader',
        parent=styles['Heading2'],
        fontSize=14,
        textColor='black',
        spaceAfter=6,
        spaceBefore=12,
        fontName='Helvetica-Bold',
        borderWidth=0,
        borderPadding=0,
        borderColor='black',
        borderRadius=0,
    )
    
    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['BodyText'],
        fontSize=10,
        textColor='black',
        spaceAfter=6,
        alignment=TA_LEFT,
        fontName='Helvetica'
    )
    
    # Build document
    story = []
    
    # Add name/title
    story.append(Paragraph(parsed['name'], title_style))
    story.append(Spacer(1, 0.2*inch))
    
    # Add sections
    for section in parsed['sections']:
        story.append(Paragraph(f"<b>{section['title']}</b>", section_style))
        story.append(Paragraph(section['content'], body_style))
        story.append(Spacer(1, 0.1*inch))
    
    # Add footer
    story.append(Spacer(1, 0.3*inch))
    footer_style = ParagraphStyle('Footer', parent=styles['Normal'], fontSize=8, 
                                  textColor='gray', alignment=TA_CENTER)
    story.append(Paragraph("Generated by res-gen | AI Resume Generator", footer_style))
    
    doc.build(story)
    return str(pdf_file)

def compile_latex_to_pdf(latex_content: str) -> str:
    """
    Compiles LaTeX content to PDF.
    Falls back to simple PDF generation if pdflatex is not available.
    """
    # Try pdflatex first
    session_id = str(uuid.uuid4())
    tex_file = TEMP_DIR / f"{session_id}.tex"
    pdf_file = TEMP_DIR / f"{session_id}.pdf"
    
    # Check if pdflatex exists
    try:
        subprocess.run(["pdflatex", "--version"], 
                      stdout=subprocess.PIPE, 
                      stderr=subprocess.PIPE,
                      timeout=5)
        has_pdflatex = True
    except (FileNotFoundError, subprocess.TimeoutExpired):
        has_pdflatex = False
    
    if has_pdflatex:
        # Write latex content to file
        with open(tex_file, "w", encoding="utf-8") as f:
            f.write(latex_content)
            
        try:
            process = subprocess.run(
                ["pdflatex", "-interaction=nonstopmode", "-output-directory", str(TEMP_DIR), str(tex_file)],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                timeout=10
            )
            
            if process.returncode == 0 and pdf_file.exists():
                return str(pdf_file)
        except Exception as e:
            print(f"pdflatex failed: {e}, falling back to simple PDF")
    
    # Fallback to simple PDF generation
    print("Using simple PDF generation (pdflatex not available)")
    return create_simple_pdf(latex_content)
